Repository spryker-shop/suite, pull requests merged in 2021-05, with the labels that each got.

#784 CI: Add MP tests and build to validation job
  .github/workflows/ci.yml
  angular.json
  frontend/merchant-portal/entry-points.js
  frontend/merchant-portal/mp-paths.js
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.mp.json
  yarn.lock
Labels: ready-for-release

#792 Sync and fix up dependencies
  composer.json
  composer.lock
Labels: dependencies

#748 [WIP] PHP8 GA CI
  .github/workflows/ci.yml
  composer.json
  composer.lock
  deploy.ci.api.mariadb.yml
Labels: improvement

#794 TE-5922 Use PHPUnit9 for split
  composer.json
  composer.lock
Labels: dependencies
