Repository spryker-shop/suite, pull requests merged in 2024-09, with the labels that each got.

#1586 CC-34258: Fixed data-import step to support multiselect product attributes.
  src/Pyz/Zed/DataImport/Business/Model/ProductAbstract/ProductAbstractHydratorStep.php
Labels: request-review

#1598 FRW-7213 Fixed CI.
  deploy.ci.acceptance.yml
Labels: bug

#1607 AE-57 Quarterly update of Dependency Overview
  dependency-overview.json
Labels: internal

#1603 FRW-9025 Added date-time configurator to robot tests.
  deploy.ci.acceptance.mariadb.robot.yml
Labels: bug
