Repository spryker-shop/suite, pull requests merged in 2025-04, with the labels that each got.

#1719 SSP-829 Added missing translation.
  data/import/common/common/glossary.csv
Labels: run-compatibility-ci

#1728 FRW-10118 Updated evaluator version.
  composer.json
  composer.lock
Labels: bug, internal, run-latest-ci

#1735 FRW-10317 Upgrade Ubuntu version in CI
  .github/workflows/ci.yml
Labels: run-latest-ci, run-compatibility-ci
